### ISSUE TITLE
Incorrect values

### ISSUE THREAD

**Issue by krnelpanic** [matthias-bs/ESP32_ATC_MiThermometer_Library#1]
Hi!
I really appreciate the dedicated work on this project, I did countless tests without success on this model.

I installed your custom firmware and library from Arduino repository.
IDE 1.8.19
Fixed BLEScan.cpp

```
          } //else if (!m_wantDuplicates && !found) {   // if no callback and not want duplicate, and not already in vector, record it
          if (!m_wantDuplicates && !found) { 
```

Result:

Sensor0:
102.41°C
97.73%
3.594V
43%
-58dBm

Sensor1:
107.53°C
87.48%
59.401V
60%
-59dBm

Devices found: 7

At the display 29.7C 43% for sensor 0 and 29.8 44% for sensor1

What am I doing wrong?

**Comment by matthias-bs** [comment]
Could you please provide all information about the sensor firmware which you are using? There are various different encodings of sensor values and I just implemented the code for the firmware I chose.

**Comment by krnelpanic** [comment]
Used your [firmware](https://github.com/atc1441/ATC_MiThermometer/blob/master/ATC_Thermometer.bin)
I flashed with this [one](https://github.com/pvvx/ATC_MiThermometer/raw/master/ATC_v37d.bin) and now is working well

Sensor0:
30.55°C
48.42%
2.387V
20%
-70dBm


Sensor1:
29.84°C
50.72%
2.493V
32%
-51dBm

Devices found: 7
